Repository flux3dp/swiftray, pull requests merged in 2022-09, with the labels that each got.

#333 Update CMakeLists.txt for sentry option
  CMakeLists.txt
Labels: size/M

#324 Add direction control by 45 degrees
  src/canvas/controls/line.cpp
  src/canvas/controls/path-draw.cpp
  src/canvas/controls/transform.cpp
Labels: size/L

#326 Change wheel control to update scale only
  src/canvas/canvas.cpp
  src/windows/preview-window.cpp
Labels: size/M

#334 Bug/fix release build workflow
  .github/workflows/build-release.yml
Labels: size/S

#335 Update win64 & cmake(linux) build by workflow_dispatch
  .github/workflows/build-cmake-macOS-Qt-5_15_2.yml
  .github/workflows/build-qmake-macos-Qt-5_15_2.yml
  .github/workflows/build-win64-mingw-Qt-5_15_3.yml
  .github/workflows/cmake.yml
Labels: size/L

#325 Add drop file for .dxf
  src/windows/mainwindow.cpp
Labels: size/XS

#320 Feature/add boundary for generated path
  i18n/zh-Hant-TW.qm
  i18n/zh-Hant-TW.ts
  src/shape/shape.cpp
  src/toolpath_exporter/generators/dirty-area-outline-generator.h
  src/toolpath_exporter/generators/gcode-generator.h
  src/toolpath_exporter/generators/preview-generator.h
  src/toolpath_exporter/toolpath-exporter.cpp
  src/toolpath_exporter/toolpath-exporter.h
  src/widgets/panels/doc-panel.cpp
  src/windows/mainwindow.cpp
  src/windows/mainwindow.h
Labels: size/L

#337 Bug/change wheel event to update scroll
  src/canvas/canvas.cpp
  src/windows/preview-window.cpp
Labels: size/M

#340 Add cursor change when holding space and transform shape
  src/canvas/canvas.cpp
Labels: size/S

#341 Add check layer when multi select
  src/canvas/controls/select.cpp
Labels: size/S

#338 Bug/replace svgpp by qsvg handler
  CMakeLists.txt
  src/canvas/canvas.cpp
  src/canvas/canvas.h
  src/parser/CMakeLists.txt
  src/parser/my_qsvg_handler.cpp
  src/parser/my_qsvg_handler.h
  src/windows/mainwindow.cpp
Labels: size/XXL

#342 Fix bug when select without shape
  src/canvas/controls/select.cpp
Labels: size/XS

#343 resize the svg file
  src/canvas/canvas.cpp
  src/windows/mainwindow.cpp
Labels: size/XS

#339 Fix bug of click change scale & wheel change scale
  src/canvas/canvas.cpp
  src/windows/mainwindow.cpp
Labels: size/XS

#344 Version update to 1.0.2
  CMakeLists.txt
  swiftray.pro
Labels: size/XS

#347 Bug/update dxf reader
  src/parser/dxf_iface.cpp
  src/parser/dxf_iface.h
Labels: size/L

#346 Feature/add japanese
  i18n/zh-Hant-JP.qm
  i18n/zh-Hant-JP.ts
  src/main.cpp
  src/windows/preferences-window.cpp
  swiftray.pro
Labels: size/XXL

#348 Update transform with group
  src/parser/my_qsvg_handler.cpp
Labels: size/XS
