Repository flux3dp/swiftray, pull requests merged in 2022-10, with the labels that each got.

#349 Fixed bug in Japanese translation
  i18n/ja-JP.qm
  i18n/ja-JP.ts
  qml.qrc
  src/main.cpp
  swiftray.pro
Labels: size/XS

#352 Add dxf read arc
  src/parser/dxf_iface.cpp
  src/parser/dxf_iface.h
Labels: size/M

#353 Fix unexpected trigger of soft limit alarm
  src/toolpath_exporter/generators/gcode-generator.h
  src/toolpath_exporter/toolpath-exporter.cpp
Labels: size/M

#354 change-rotary-UI
  src/windows/rotary_setup.cpp
  src/windows/rotary_setup.h
  src/windows/rotary_setup.ui
Labels: size/L

#358 Release/1.1.0
  src/layer.cpp
  src/layer.h
  src/windows/rotary_setup.ui
Labels: size/M
