Repository flux3dp/swiftray, pull requests merged in 2022-11, with the labels that each got.

#362 Add warning message when framing item over range
  src/windows/mainwindow.cpp
Labels: size/XS

#363 Bug/add backlash to bb and transform UI range
  src/document-serializer.h
  src/widgets/panels/layer-params-panel.cpp
  src/widgets/panels/transform-panel.ui
Labels: size/S

#366 Change scale define in my qsvg
  src/canvas/canvas.cpp
  src/parser/my_qsvg_handler.cpp
Labels: size/XS

#368 Fix native gesture to change scale small than 10%
  src/canvas/canvas.cpp
  src/canvas/canvas.h
Labels: size/L

#365 Add select check object inside or not
  src/canvas/controls/select.cpp
  src/canvas/controls/select.h
Labels: size/S

#372 Update jogging panel show current
  src/widgets/panels/jogging-panel.ui
Labels: size/XS

#370 make sure Widget won't block by other UI when show by action
  src/windows/mainwindow.cpp
Labels: size/M

#373 Add check line when select inside
  src/canvas/controls/select.cpp
Labels: size/XS

#371 Update classic & essential UI
  classicUI.ini
  essentialUI.ini
  src/windows/mainwindow.ui
Labels: size/S

#374 Add rotary info to QSetting
  src/widgets/panels/doc-panel.cpp
  src/widgets/panels/doc-panel.ui
  src/windows/mainwindow.cpp
  src/windows/rotary_setup.cpp
  src/windows/rotary_setup.h
  src/windows/rotary_setup.ui
Labels: size/M

#375 Add mode exit when mode switch
  src/canvas/canvas.cpp
  src/canvas/canvas.h
  src/windows/mainwindow.cpp
Labels: size/S

#367 Add rotary mirror function
  src/toolpath_exporter/generators/dirty-area-outline-generator.h
  src/toolpath_exporter/generators/gcode-generator.h
  src/toolpath_exporter/generators/preview-generator.h
  src/toolpath_exporter/toolpath-exporter.cpp
  src/toolpath_exporter/toolpath-exporter.h
  src/widgets/panels/layer-params-panel.ui
  src/widgets/panels/transform-panel.ui
  src/windows/mainwindow.cpp
  src/windows/preview-window.cpp
  src/windows/preview-window.h
  src/windows/rotary_setup.cpp
Labels: size/L

#377 Fix filepath with non ascii char
  src/parser/pdf2svg.cpp
Labels: size/XS

#379 Set soft reset as the first cmd when connecting
  src/executor/machine_setup_executor.cpp
Labels: size/S
